require('dotenv').config()
const express = require('express')
const connectDB = require('./config/db')
const userapi = require('./api/userapi')
const app = express()
app.use(express.json())
connectDB()
app.use('/users', userapi)
app.listen(process.env.PORT, () => {
    console.log(`Server is running on `,process.env.PORT)
    })